; Each boss needs an entry in this file.

; These are full palette sets allowing maximum flexability.
; For instance, the background could flash when a boss is damaged.

    COLOR_PALETTE_BOSS 000              ; Vampire        $00
    COLOR_PALETTE_BOSS 001              ; Hydra          $01
    COLOR_PALETTE_BOSS blue             ; Medusa         $02
    COLOR_PALETTE_BOSS 003              ; Megapede       $03
    COLOR_PALETTE_BOSS blue             ; Davias         $04
    COLOR_PALETTE_BOSS 005              ; Golem          $05
    COLOR_PALETTE_BOSS blue             ; Cyclops        $06
    COLOR_PALETTE_BOSS blue             ; Chimera        $07
    COLOR_PALETTE_BOSS blue             ; Kary           $08
    COLOR_PALETTE_BOSS blue             ; Kraken         $09
    COLOR_PALETTE_BOSS blue             ; Ifrit          $0a
    COLOR_PALETTE_BOSS blue             ; Lich           $0b
    COLOR_PALETTE_BOSS blue             ; Garuda         $0c
    COLOR_PALETTE_BOSS blue             ; Dragon         $0d
    COLOR_PALETTE_BOSS blue             ; Julius 2       $0e
    COLOR_PALETTE_BOSS blue             ; Dragon Zombie  $0f
    COLOR_PALETTE_BOSS 016              ; Jackal         $10
    COLOR_PALETTE_BOSS blue             ; Julius 3       $11
    COLOR_PALETTE_BOSS blue             ; Metal Crab     $12
    COLOR_PALETTE_BOSS blue             ; Mantis Ant     $13
    COLOR_PALETTE_BOSS 020              ; Red Dragon     $14
