RSRESET
; Used by windows and swapped out for line effects.
DEF BGP_SPECIAL    RB 1

; Default palette. While there are a limited number palettes available it makes sense to have a catch-all.
DEF BGP_BRIDGE     RB 0
DEF BGP_FLOATROCK  RB 0
DEF BGP_PALISADE   RB 0
DEF BGP_SAND       RB 0
DEF BGP_SNAG       RB 0
DEF BGP_DEFAULT    RB 1

; Anything green.
DEF BGP_LEAVES     RB 0
DEF BGP_SPROUT     RB 0
DEF BGP_TREE       RB 0
DEF BGP_GREEN      RB 1

; Anything that needs blue.
; The original general GBC auto-colorization palette.
; It has a light green and a dark blue.
; This has been used for the Lazy DX colorization for quite some time.
DEF BGP_CASKET     RB 0
DEF BGP_CRYSTAL    RB 0
DEF BGP_DOCK       RB 0
DEF BGP_OCEAN      RB 0
DEF BGP_RIVER      RB 0
DEF BGP_SHORE      RB 0
DEF BGP_SKY        RB 0
DEF BGP_BLUEGREEN  RB 1

; Brown is currently used very limitedly.
DEF BGP_BARK       RB 0
DEF BGP_END        RB 0
DEF BGP_LIGHT      RB 0
DEF BGP_BROWN      RB 1

; Uses two shades of blue.
DEF BGP_FALLS      RB 0
DEF BGP_SNOW       RB 0
DEF BGP_BLUE       RB 1
