INCLUDE "include/macros.inc"

; Color palettes. Each includes sets of eight background palettes and eight object palettes for:
; * Normal colors.
; * Blind effect.
; * Fullscreen flash script command.
; * Boss damage blink.

; Backgrounds currently only use palette 0.

; Sprites use these palettes:
; 0 Player.
; 1 Player attack
; 2 Snowman.
; 3 follower.
; 4 Enemy projectile.
; 5, 6, and 7 for everything else (NPCs, enemies, and bosses).

; Loaded at boot.
    COLOR_PALETTE init
